# Generated by Django 5.1.4 on 2025-01-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_tarefa', '0002_tag_projeto_tags_tarefa_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('To Do', 'todo'), ('Em andamento', 'em_andamento'), ('Feito', 'feito')], default='todo', max_length=20),
        ),
    ]
