# Generated by Django 5.1.4 on 2025-01-27 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_tarefa', '0003_alter_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
